title: My digital brain
author: joergi
description: > # this means to ignore newlines until "baseurl:"
 this is my test blog
 isn't it beautiful?
 
baseurl: "https://joergi.github.io/blog"

# social links
twitter_username: joergi_77 # DO NOT include the @ character, or else the build will fail!
github_username:  joergi # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
